import { mkdirSync, readFileSync, writeFileSync } from 'fs';
import { spawnSync } from 'child_process';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');

const zh = JSON.parse(readFileSync(join(root, 'locales/zh-CN.json'), 'utf8'));
const en = JSON.parse(readFileSync(join(root, 'locales/en.json'), 'utf8'));

writeFileSync(
  join(root, 'js/lib/messages.js'),
  `/** Generated by npm run build — do not edit. */\nexport const MESSAGES = ${JSON.stringify({ 'zh-CN': zh, en }, null, 2)};\n`,
);

mkdirSync(join(root, 'assets'), { recursive: true });

const result = spawnSync(
  'npx',
  [
    'esbuild',
    'js/pages/home.js',
    'js/pages/session.js',
    '--bundle',
    '--format=iife',
    '--target=es2020',
    '--outdir=assets',
    '--entry-names=[name]',
  ],
  { cwd: root, shell: true, stdio: 'inherit' },
);

if (result.status !== 0) {
  process.exit(result.status ?? 1);
}

console.log('Built assets/home.js and assets/session.js');
